name: Unit Test

on: [pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 16.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version}}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: 'https://npm.pkg.github.com'
          always-auth: true
          scope: '@HJyup'
      - name: yarn install
        run: yarn install
        env:
          NODE_AUTH_TOKEN: ${{ secrets.ENV_TOKEN }}
      - name: test
        run: yarn test